name: Super Linter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Super-Linter
        run: |
          echo "github_token: ${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "enabled_linters: ansible,cfn,docker,golang,html,java,javascript,json,markdown,perl,powershell,python,ruby,shell,yaml" >> $GITHUB_ENV

      - name: Run Super-Linter
        uses: github/super-linter@v3
        with:
          entryPoint: |
            sh /action/lib/linter.sh
          args: -c .github/linters.yml
